from __future__ import annotations

from typing import Protocol

from shared.schemas.camera import CameraStatus, CaptureModeInfo, CameraProperty
from shared.schemas.recording import RecordingConfig, RecordingStatus


class ICaptureService(Protocol):
    async def connect(self, serial: str | None = None) -> CameraStatus: ...

    async def disconnect(self) -> None: ...

    def get_status(self) -> CameraStatus: ...

    def list_modes(self) -> list[CaptureModeInfo]: ...

    def get_properties(self) -> list[CameraProperty]: ...

    async def set_properties(self, values: dict[str, float | int | str]) -> list[CameraProperty]: ...

    async def start_preview(self, mode: str | None = None, pixel_format: str = "mono8") -> None: ...

    async def stop_preview(self) -> None: ...

    async def start_recording(self, config: RecordingConfig) -> RecordingStatus: ...

    async def stop_recording(self, recording_id: str) -> RecordingStatus: ...

    def get_recording_status(self, recording_id: str) -> RecordingStatus: ...
